repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      # Python specific
      - id: debug-statements # prevents commiting calls to breakpoint()
      - id: double-quote-string-fixer # replaces " with ' in string literals
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--skip-string-normalization]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.19.1
    hooks:
      - id: stylua-system
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #   - id: detect-secrets
        #      args: [--baseline, .secrets.baseline]
        #
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    # Choose either the 'alejandra' or 'alejandra-system' hook
    # depending on what pre-requisites you have:
    hooks:
      # No prerequisites
      # - id: alejandra

      # # Requires Nix to be previously installed in the system
      # - id: alejandra-nix
      #
      # # Requires Alejandra to be previously installed in the system
      - id: alejandra-system
