[tools]
uv = "latest"

[tasks.rebuild-chris]
# run = "sudo nixos-rebuild switch --flake ~/dotfiles#chris"
run = "nh os switch ~/dotfiles -H chris"

[tasks.rebuild-sam]
run = "nixos-rebuild switch --flake ~/dotfiles#sam --target-host sam --sudo"

[tasks.rebuild-ben]
run = "nixos-rebuild switch --flake ~/dotfiles#ben --target-host ben --sudo"

[tasks.rebuild-anton]
run = "nixos-rebuild switch --flake ~/dotfiles#anton --target-host anton --sudo"

[tasks.install-python-tools]
run = [
  "uv tool install --upgrade apyanki",
  "uv tool install --upgrade awscli",
  "uv tool install --upgrade mdformat --with mdformat-gfm",
  "uv tool install --upgrade pre-commit",
  "uv tool install --upgrade ruff"
]

[tasks.stow]
run = [
  "stow -t ~ -d stow nvim",
  "stow -t ~ -d stow awesome",
  "stow -t ~ -d stow nix",
  "stow -t ~ -d stow ghostty"
]

[tasks.stow-delete]
run = [
  "stow -D -t ~ -d stow nvim",
  "stow -D -t ~ -d stow awesome",
  "stow -D -t ~ -d stow nix",
  "stow -D -t ~ -d stow ghostty"
]
