#!/bin/bash

cd /home/denis/Sync/books 
book_name=$(fd . | rofi -dmenu -matching fuzzy -sorting-method fzf -sort -i)

if [  -z "$book_name" ]
then
    echo 'No book selected'
else
    sioyek "$book_name"
fi
