#! /usr/bin/env python3
import pathlib
import re
import sys


REMOVE_PATTERS = [' (z-lib.org)']

def main():

    path = pathlib.Path()
    if len(sys.argv) == 1:
        print('You must pass a file name')
        return 1

    file_name = sys.argv[1]

    file = path / file_name

    if not file.exists():
        print(f"'{file.absolute()}' is not a file.")
        return 1

    new_name = file.stem
    
    for pattern in REMOVE_PATTERS:
        new_name = new_name.replace(pattern, '')

    REMOVE_BRACKETS = r'[\(\[].*?[\)\]]'
    new_name = re.sub(REMOVE_BRACKETS, '', new_name)
    new_name = re.sub(r'-+', '-', new_name)
    new_name = re.sub(r'-$', '', new_name)
    new_name = new_name.replace(' ', '-')
    new_name = new_name.replace(',', '')
    new_name = new_name.replace('[', '')
    new_name = new_name.replace(']', '')
    new_name = new_name.replace('’', '')
    new_name = new_name.replace('.', '')
    new_name = new_name.lower()
    # print(new_name + file.suffix)
    file.rename(new_name + file.suffix)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
