#! /bin/bash

OBSIDIAN_FOLDER="$HOME/Sync/Notes/Current"
FILE_PATH="$OBSIDIAN_FOLDER/Weekly/$(date +'%Y-%W.md')"

cd "$OBSIDIAN_FOLDER"
if [ -f  "$FILE_PATH" ]; then
    echo "$FILE_PATH"
else
    echo '#' "$(date +'%Y-%W.md')" > "$FILE_PATH"
fi
nvim -c 'lua center_and_change_colorscheme()' $FILE_PATH
