session_name: core
windows:
  - window_name: recap
    start_directory: "~/github.com/recap-technologies/core"
    panes:
      -
      -
  - window_name: sam
    start_directory: "~/github.com/denismaciel/sam"
    panes:
      -
      -
  - window_name: dotfiles
    start_directory: "~/dotfiles"
    panes:
      -
      -
