session_name: core
windows:
  - window_name: recap-top
    start_directory: "~/work/core"
    panes:
      -
      -
  - window_name: recap-github-actions
    start_directory: "~/work/core/.github"
    panes:
      -
      -
  - window_name: recap-pycap
    start_directory: "~/work/core/pycap"
    panes:
      -
      -
  - window_name: recap-backend
    start_directory: "~/work/core/backend"
    panes:
      -
      -
  - window_name: recap-frontend
    start_directory: "~/work/core/recap-app"
    panes:
      -
      -
  - window_name: sam-top
    start_directory: "~/github.com/denismaciel/sam"
    panes:
      -
      -
  - window_name: sam-web
    start_directory: "~/github.com/denismaciel/sam/web"
    panes:
      -
      -
  - window_name: sam-server
    start_directory: "~/github.com/denismaciel/sam/server"
    panes:
      -
      -
  - window_name: dotfiles
    start_directory: "~/dotfiles"
    panes:
      -
      -
