session_name: core
windows:
  - window_name: recap
    start_directory: "~/github.com/recap-technologies/core"
    panes:
      -
      -
  - window_name: sam-top
    start_directory: "~/github.com/denismaciel/sam"
    panes:
      -
      -
  - window_name: sam-web
    start_directory: "~/github.com/denismaciel/sam/web"
    panes:
      -
      -
  - window_name: sam-server
    start_directory: "~/github.com/denismaciel/sam/server"
    panes:
      -
      -
  - window_name: dotfiles
    start_directory: "~/dotfiles"
    panes:
      -
      -
