session_name: core
windows:
  # - window_name: top
  #   start_directory: "~/work/core"
  #   panes:
  #     -
  #     -
  # - window_name: github-actions
  #   start_directory: "~/work/core/.github"
  #   panes:
  #     -
  #     -
  # - window_name: pycap
  #   start_directory: "~/work/core/pycap"
  #   panes:
  #     -
  #     -
  # - window_name: dwh
  #   start_directory: "~/work/core/dwh"
  #   panes:
  #     -
  #     -
  # - window_name: backend
  #   start_directory: "~/work/core/backend"
  #   panes:
  #     -
  #     -
  # - window_name: frontend
  #   start_directory: "~/work/core/recap-app"
  #   panes:
  #     -
  #     -
  - window_name: praisepenguin
    start_directory: "~/github.com/denismaciel/praise-penguin"
    panes:
      -
      -


  - window_name: praisepenguin-web
    start_directory: "~/github.com/denismaciel/praise-penguin/web"
    panes:
      -
      -

  - window_name: dotfiles
    start_directory: "~/dotfiles"
    panes:
      -
      -

  - window_name: newsboat
    start_directory: "~/dotfiles"
    panes:
      - newsboat

  - window_name: blog
    start_directory: "~/github.com/denismaciel/denismaciel.com"
    panes:
      -
      -

  - window_name: lighthouse
    start_directory: "~/github.com/monasticai/lighthouse/"
    panes:
      -
      -

  - window_name: ai
    start_directory: "~/github.com/denismaciel/ai"
    panes:
      -
      -
