session_name: default
windows:
    - window_name: pen-0
      panes:
          - shell_command: cd ~/Code/pen-platform-0
          - shell_command: cd ~/Code/pen-platform-0
    - window_name: pen-1
      panes:
          - shell_command: cd ~/Code/pen-platform-1
          - shell_command: cd ~/Code/pen-platform-1
    - window_name: pen-2
      panes:
          - shell_command: cd ~/Code/pen-platform-2
          - shell_command: cd ~/Code/pen-platform-2
    - window_name: trainer
      panes:
          - shell_command: cd ~/Code/pen-trainer
          - shell_command: cd ~/Code/pen-trainer
    - window_name: openvpn
      panes:
          - shell_command: sudo openvpn --config /etc/openvpn/collins-vpn.conf
    - window_name: metaflow
      panes:
          - shell_command: cd ~/Code/metaflow
          - shell_command: cd ~/Code/metaflow

