session_name: default
windows:
    - window_name: Shell
      panes:
          - shell_command:
              - echo "Hi there, Mr. Pinto Maciel"
          - shell_command: echo "Guten Morgen, Herr Pinto Maciel"
    - window_name: Notes
      panes:
          - shell_command:
              - cd ~/Dropbox/Notes/Current/ 
              - nvim $(date +'Work_%Y-%W').md

