#! /usr/bin/env bash

# Capture the content of the current tmux pane
tmux capture-pane -S -1000 -p > /tmp/tmux_pane_content

# Split the current window vertically and create a new pane
tmux popup -w 90% -h 90% -E "nvim -c 'normal G' /tmp/tmux_pane_content"
