#! /usr/bin/env python3
#
import subprocess
from collections import Counter
from datetime import datetime
from datetime import timedelta


REPO_PATH = '/home/denis/work/core'
NUMBER_OF_WEEKS = 2

delta = datetime.now() - timedelta(weeks=NUMBER_OF_WEEKS)

cmd = [
    'git',
    '-C',
    REPO_PATH,
    'log',
    '--since=' + delta.strftime('%Y-%m-%d'),
    '--format=%aN',
    'origin/main',
]
output = subprocess.check_output(cmd).decode('utf-8')

count = Counter(output.splitlines())

max_len = max(len(author) for author in count.keys())

for author, count in count.most_common():
    length = len(author)
    spaces = max_len - length + 2
    author = author + ' ' * spaces
    print(author, count)
