#! /usr/bin/env python
import argparse
import datetime

parser = argparse.ArgumentParser('')
parser.add_argument(
    '--kind',
    choices=[
        'risk-model',
        'dagster',
        'backend',
        'customer-app',
        'operations-app',
        'transaction-tagging',
    ],
    required=True,
)
args = parser.parse_args()

print(f'{args.kind}-v{datetime.date.today()}.1')
