#! /usr/bin/env python
import argparse
import datetime

parser = argparse.ArgumentParser('')
parser.add_argument(
    '--kind',
    choices=[
        'pycap',
        'dagster',
        'backend',
        'customer-app',
        'operations-app',
        'transaction-tagging',
    ],
    default='pycap',
)
args = parser.parse_args()

print(f'{args.kind}-v{datetime.date.today()}.1')
