#!/usr/bin/env python

from datetime import datetime, timedelta
from typing import Any
import sys
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    "-s", "--start", dest="start", help="When does your day start?",
)
parser.add_argument("-e", "--end", dest="end", help="When does your day end?")

args = parser.parse_args()

START = args.start
if START is None:
    now = datetime.now()
    hour = now.hour
    minute = "00" if now.minute < 30 else "30"
    START = f"{hour}:{minute}"

END = args.end or "18:00"


def timesheet(start: str, end: str) -> Any:
    fmt = "%H:%M"
    s = datetime.strptime(start, fmt)
    e = datetime.strptime(end, fmt)
    l = [s]
    next = s + timedelta(minutes=30)
    while True:
        if next >= e:
            break
        l.append(next)
        next += timedelta(minutes=30)
    l.append(e)
    return l

r = timesheet(START, END)

def fmt(i):
    return datetime.strftime(i, "%H.%M")


ts = [f"- [ ] {fmt(i)} {fmt(j)}" for i, j in zip(r[:-1], r[1:])]

sys.stdout.write("\n".join(ts))
