#! /bin/bash

AUDIO_FILE_NAME=/home/denis/Sync/convert-audio/$(date +"%Y%m%d-%H%M.mp3")
TRANSCRIPTION_FILE_NAME=/home/denis/Sync/convert-audio/$(date +"%Y%m%d-%H%M.txt")
echo Saving recording to $AUDIO_FILE_NAME
arecord --format=cd "$AUDIO_FILE_NAME"

ABS_PATH=$(realpath "$AUDIO_FILE_NAME")

if [ $? -ne 0 ]; then
    echo "Failed to get the absolute path" >&2
    exit 1
fi

WHISPER_V3=/home/denis/experiments/whisper-v3
$WHISPER_V3/venv/bin/python3 $WHISPER_V3/transcribe.py "$ABS_PATH" "$TRANSCRIPTION_FILE_NAME"
