live_config_reload = true
# import = ["~/.config/alacritty/rose-pine-moon.toml"]
import = ["~/.config/alacritty/nord.toml"]

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Blex Mono Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
opacity = 1
